### ISSUE TITLE
Needs update for aiohttp 2.0

### ISSUE THREAD

**Issue by patrick-jones** [sloria/webtest-aiohttp#3]
Apparently there are backwards-incompatible changes in aiohttp 2.0.  At the very least, you can no longer import `web_reqgrep ` from `aiohttp` as in done [here](https://github.com/sloria/webtest-aiohttp/blob/master/webtest_aiohttp.py#L35-L37).

**Comment by sloria** [comment]
Thanks @patrick-jones . I would certainly review and merge a PR fixing 2.0 compatibility. =)

**Comment by sloria** [comment]
webtest-aiohttp 2.0.0 now supports aiohttp 2.
